name: ubuntu-master

on:
  push:
    branches:
      - master
    paths-ignore:
      - AUTHORS
      - README.md
  pull_request:
    branches:
      - master
    paths-ignore:
      - AUTHORS
      - README.md

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala:
          - 2.11.12
          - 2.12.14
        tarantool:
          - 2.8
    steps:
      - uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: "adopt@1.8"
      - name: Cache docker images
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: ${{ runner.os }}-docker-layer-cache-${{ matrix.tarantool }}
          restore-keys: |
            ${{ runner.os }}-docker-layer-cache-
      - name: Cache SBT
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ matrix.scala }}-${{ hashFiles('**/build.sbt') }}
      - name: Run tests
        env:
          TARANTOOL_VERSION: ${{ matrix.tarantool }}
          TARANTOOL_SERVER_USER: root
          TARANTOOL_SERVER_GROUP: root
          TARANTOOL_CLUSTER_COOKIE: testapp-cluster-cookie-${{ matrix.scala }}-${{ matrix.tarantool }}
        run: sbt ++${{ matrix.scala }} coverageOn test coverageReport coverageOff
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scala:
          - 2.11.12
          - 2.12.14
    steps:
      - uses: actions/checkout@v2
      - name: Setup Scala
        uses: olafurpg/setup-scala@v11
        with:
          java-version: "adopt@1.8"
      - name: Cache SBT
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ matrix.scala }}-${{ hashFiles('**/build.sbt') }}
      - name: Check formatting
        run: sbt ++${{ matrix.scala }} scalafmtSbtCheck scalafmtCheck test:scalafmtCheck
